'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property homepage() As String
            Get
                Return CType(Me("homepage"),String)
            End Get
            Set
                Me("homepage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("216, 214, 211")>  _
        Public Property StyleBrowser0() As Global.System.Drawing.Color
            Get
                Return CType(Me("StyleBrowser0"),Global.System.Drawing.Color)
            End Get
            Set
                Me("StyleBrowser0") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("186, 185, 183")>  _
        Public Property StyleBrowser1() As Global.System.Drawing.Color
            Get
                Return CType(Me("StyleBrowser1"),Global.System.Drawing.Color)
            End Get
            Set
                Me("StyleBrowser1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("216, 214, 211")>  _
        Public Property StyleBrowser2() As Global.System.Drawing.Color
            Get
                Return CType(Me("StyleBrowser2"),Global.System.Drawing.Color)
            End Get
            Set
                Me("StyleBrowser2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("64, 64, 64")>  _
        Public Property StyleBrowser3() As Global.System.Drawing.Color
            Get
                Return CType(Me("StyleBrowser3"),Global.System.Drawing.Color)
            End Get
            Set
                Me("StyleBrowser3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DimGray")>  _
        Public Property StyleBrowser4() As Global.System.Drawing.Color
            Get
                Return CType(Me("StyleBrowser4"),Global.System.Drawing.Color)
            End Get
            Set
                Me("StyleBrowser4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("238, 236, 233")>  _
        Public Property StyleBrowser5() As Global.System.Drawing.Color
            Get
                Return CType(Me("StyleBrowser5"),Global.System.Drawing.Color)
            End Get
            Set
                Me("StyleBrowser5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("216, 214, 211")>  _
        Public Property StyleBrowser6() As Global.System.Drawing.Color
            Get
                Return CType(Me("StyleBrowser6"),Global.System.Drawing.Color)
            End Get
            Set
                Me("StyleBrowser6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("238, 236, 233")>  _
        Public Property StyleBrowser7() As Global.System.Drawing.Color
            Get
                Return CType(Me("StyleBrowser7"),Global.System.Drawing.Color)
            End Get
            Set
                Me("StyleBrowser7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property StyleBrowser8() As Global.System.Drawing.Color
            Get
                Return CType(Me("StyleBrowser8"),Global.System.Drawing.Color)
            End Get
            Set
                Me("StyleBrowser8") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Transparent")>  _
        Public Property StyleBrowser9() As Global.System.Drawing.Color
            Get
                Return CType(Me("StyleBrowser9"),Global.System.Drawing.Color)
            End Get
            Set
                Me("StyleBrowser9") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("229, 226, 222")>  _
        Public Property StyleBrowser10() As Global.System.Drawing.Color
            Get
                Return CType(Me("StyleBrowser10"),Global.System.Drawing.Color)
            End Get
            Set
                Me("StyleBrowser10") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("86, 75, 68")>  _
        Public Property StyleBrowser11() As Global.System.Drawing.Color
            Get
                Return CType(Me("StyleBrowser11"),Global.System.Drawing.Color)
            End Get
            Set
                Me("StyleBrowser11") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("229, 226, 222")>  _
        Public Property StyleBrowser12() As Global.System.Drawing.Color
            Get
                Return CType(Me("StyleBrowser12"),Global.System.Drawing.Color)
            End Get
            Set
                Me("StyleBrowser12") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("86, 75, 68")>  _
        Public Property StyleBrowser13() As Global.System.Drawing.Color
            Get
                Return CType(Me("StyleBrowser13"),Global.System.Drawing.Color)
            End Get
            Set
                Me("StyleBrowser13") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property StyleBrowser14() As Global.System.Drawing.Color
            Get
                Return CType(Me("StyleBrowser14"),Global.System.Drawing.Color)
            End Get
            Set
                Me("StyleBrowser14") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IsDarkTheme() As Boolean
            Get
                Return CType(Me("IsDarkTheme"),Boolean)
            End Get
            Set
                Me("IsDarkTheme") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TopSitesAddress() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("TopSitesAddress"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("TopSitesAddress") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TopSitesName() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("TopSitesName"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("TopSitesName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TopSitesImages() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("TopSitesImages"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("TopSitesImages") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BasicHistory() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("BasicHistory"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("BasicHistory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BookAddress() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("BookAddress"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("BookAddress") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BookNames() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("BookNames"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("BookNames") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BookImages() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("BookImages"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("BookImages") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Clover.My.MySettings
            Get
                Return Global.Clover.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
